/** Nomes dos canais IPC, agrupados por domínio (docs/04-contratos-ipc.md §4). */
export const CH = {
  library: {
    home: 'library:home',
    list: 'library:list',
    get: 'library:get',
    rename: 'library:rename',
    setFavorite: 'library:setFavorite',
    setReadStatus: 'library:setReadStatus',
    removeFromContinue: 'library:removeFromContinue',
    delete: 'library:delete',
    stats: 'library:stats',
  },
  importer: {
    pickFiles: 'import:pickFiles',
    start: 'import:start',
    cancel: 'import:cancel',
    resolveDuplicate: 'import:resolveDuplicate',
    getJob: 'import:getJob',
    onProgress: 'import:progress',
    onLibraryChanged: 'library:changed',
  },
  collections: {
    list: 'collections:list',
    get: 'collections:get',
    create: 'collections:create',
    update: 'collections:update',
    delete: 'collections:delete',
    addItems: 'collections:addItems',
    removeItems: 'collections:removeItems',
    reorder: 'collections:reorder',
    setCover: 'collections:setCover',
    pickCoverImage: 'collections:pickCoverImage',
    membership: 'collections:membership',
    nextToRead: 'collections:nextToRead',
  },
  reader: {
    open: 'reader:open',
    setPage: 'reader:setPage',
    savePrefs: 'reader:savePrefs',
    resetPrefs: 'reader:resetPrefs',
    complete: 'reader:complete',
    reportPageSize: 'reader:reportPageSize',
    close: 'reader:close',
  },
  settings: {
    get: 'settings:get',
    update: 'settings:update',
    resetAllReaderPrefs: 'settings:resetAllReaderPrefs',
  },
  app: {
    info: 'app:info',
    openDataFolder: 'app:openDataFolder',
    clearCache: 'app:clearCache',
    toggleFullscreen: 'app:toggleFullscreen',
    onFullscreenChanged: 'app:fullscreenChanged',
  },
} as const
